# Generated by Django 4.0.6 on 2022-07-28 19:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_race', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(verbose_name=False)),
                ('race_type', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('link', models.URLField()),
                ('goals', models.ManyToManyField(to='main_app.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Training date')),
                ('activity', models.CharField(choices=[('R', 'Run'), ('B', 'Bike'), ('S', 'Swim'), ('W', 'Weight'), ('C', 'Cross-Fit'), ('O', 'Other')], default='R', max_length=1, verbose_name='Activity')),
                ('distance', models.FloatField(verbose_name='distance - miles')),
                ('duration', models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(1)], verbose_name='duration - minutes')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.race')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.race')),
            ],
        ),
    ]
